version: "3"

services:
  shortLink:
    restart: unless-stopped
    container_name: shortLink
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - . /runner
    ports:
      - "8080:8080"

  postgres_db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./migrations/auth_go.sql:/docker-entrypoint-initdb.d/auth_go.sql
      - ./database/auth_go:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped



  redis_db:
    image: redis:latest
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${POSTGRES_PASSWORD}

